services:
  streamlit:
    build: ./streamlit_app
    container_name: spotify-recommendation-system
    ports:
      - "8501:8501"
    volumes:
      - ./data/raw:/app/data/raw:ro  # Raw data (read-only)
      - ./data/models:/app/data/models:ro  # Models (read-only)
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_ENABLEXSRFPROTECTION=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Optional: Add a PostgreSQL database for storing processed data
# postgres:
#   image: postgres:14-alpine
#   container_name: spotify-analysis-db
#   ports:
#     - "5432:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   environment:
#     - POSTGRES_USER=postgres
#     - POSTGRES_PASSWORD=postgres
#     - POSTGRES_DB=spotify_data
#   restart: unless-stopped
#   healthcheck:
#     test: ["CMD-SHELL", "pg_isready -U postgres"]
#     interval: 30s
#     timeout: 5s
#     retries: 3
#     start_period: 10s

# Optional: Add an Adminer for database management
# adminer:
#   image: adminer:latest
#   container_name: spotify-analysis-adminer
#   ports:
#     - "8080:8080"
#   restart: unless-stopped
#   depends_on:
#     - postgres

# Optional: Add a data processing service
# data-processor:
#   build: ./data_processor
#   container_name: spotify-analysis-processor
#   volumes:
#     - ./data:/app/data
#   depends_on:
#     - postgres
#   restart: on-failure

# Define volumes
# volumes:
#   postgres_data: 